name: first workflow
env:
  WORKFLOW_VAR: "This varialble is declared at the workflow level"
on:
  workflow_dispatch:
  
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script step 1
        shell: bash
        run: echo Hello World! This is the first job step 1
      - name: firstJob script step 2
        shell: bash
        run: echo Hello World! This is the first job step 2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"
  
  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "This variable is declared at the Job level"
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second job
          echo and this is a multi-line script
      - name: environment variables
        env:
          STEP_VAR: "This variable is declared at the step level"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "The following is a secret: ${{ secrets.SOME_SECRET }}
          echo "The following are default environment variables:"
          echo $GITHUB_ACTOR
          echo $GITHUB_JOB
          echo $GITHUB_REF
          
